//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedAlert.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RedAlert.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;value&quot;:&quot;אבו סנאן&quot;,&quot;name&quot;:&quot;אבו סנאן&quot;,&quot;name_en&quot;:&quot;Abu Snan&quot;,&quot;name_ru&quot;:&quot;Абу Снан&quot;,&quot;name_ar&quot;:&quot;ابو سنان&quot;,&quot;zone&quot;:&quot;גליל עליון&quot;,&quot;zone_en&quot;:&quot;Upper Galilee&quot;,&quot;zone_ru&quot;:&quot;Верхняя Галилея&quot;,&quot;zone_ar&quot;:&quot;الجليلالأعلى&quot;,&quot;countdown&quot;:30,&quot;time&quot;:&quot;30 שניות&quot;,&quot;time_en&quot;:&quot;30 Seconds&quot;,&quot;time_ru&quot;:&quot;30 секунд&quot;,&quot;time_ar&quot;:&quot;30 ثانية&quot;,&quot;lat&quot;:32.958,&quot;lng&quot;:35.172},{&quot;value&quot;:&quot;אבו קרינאת והפזורה&quot;,&quot;name&quot;:&quot;אבו קרינאת והפזורה&quot;,&quot;name_en&quot;:&quot;Abu Qrenat&quot;,&quot;name_ru&quot;:&quot;Абу Кренат&quot;,&quot;name_ar&quot;:&quot;أبو كرينات وضواحيها&quot;,&quot;zone&quot;:&quot;דרום הנגב&quot;,&quot;zone_en&quot;:&quot;Southern Negev&quot;,&quot;zo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
    }
}
